### PR TITLE
Compatibility with mongo 2.6

### PR DESCRIPTION
**Pull request by jarthod**
Hi,

First of all thanks a lot for this little gem and for the work you brought to the `mongo` gem.

If I'm correct mongodb is bringing retryable writes in 3.6 with "sessions" which may hopefully make this gem obsolete, but I don't even see an option in `mongoid` yet so in the meantime, there's `mongo_ha` :tada: 

I've just started using this gem for my project which uses mongodb across the internet and is quite often subject to network glitches and it's working great so far, I've had to make a little adjustment to be able to use it with the `mongo 2.6.x` series since they changed the `legacy_write_with_retry` method signature a little for this new "session" feature: https://github.com/mongodb/mongo-ruby-driver/blob/v2.6.2/lib/mongo/retryable.rb

This version adds support for the (optional) session parameter and is thus backward compatible with `2.5.x` so I've allowed both `mongo 2.5.x` and `2.6.x` in the `gemspec` and bumped the `mongo_ha` gem version to `2.6.0`.

BTW one question, I've seen a couple other types of exceptions interrupting mongo queries which I think may be interesting to retry too but I wanted your opinion about whether you think it would be a bad idea to retry them and if you would be interested in a PR adding them. Here are the two I'm thinking of right now:

- `Timeout::Error Took more than 180 seconds to receive data.` → this one occurs when you set the `socket_timeout` option (default is infinite) and prevents mongo from blocking indefinitely if the reply to a query is never received. Retrying that might lead to duplicate operation though as we can't be sure if it was executed or not, but that's the same thing with `Error::SocketTimeoutError` I guess?

- `Error::OperationFailure interrupted at shutdown` → I got this one a lot when doing maintenance and restarts, oddly it's *not* in the [retryable write list from mongo](https://github.com/mongodb/mongo-ruby-driver/blob/b147f783459baa2ce8e397dad59a7ae67f32c194/lib/mongo/error/operation_failure.rb#L47) but I think it should be safe to retry.

Do not hesitate if you have any question or suggestion.

Thanks

### CODE REVIEW

**Comment by jarthod** [comment]
Oh by the way I also removed the `.ruby-version` file because it had an invalid value but I can add it back with a valid ruby version if you prefer.

**Comment by reidmorrison** [comment]
Have tried to get everything in this gem directly into the mongo gem itself:
https://github.com/mongodb/mongo-ruby-driver/pull/852

As for the Timeout exception regression:
https://github.com/mongodb/mongo-ruby-driver/pull/859

In our environment we do writes between 2 data centers and I have noticed the `Error::OperationFailure interrupted at shutdown` error. Would be great to add support for it.

**Comment by reidmorrison** [comment]
Published a gem with your changes, lets continue with the above exceptions in a separate PR.

**Comment by jarthod** [comment]
That's great thanks, as the Timeout error inconsistency probably won't be fixed upstream it could be a good idea to add it in here too then? I'll make one or two PRs.

**Comment by reidmorrison** [comment]
We recently performed a DR failover test and are still getting the following errors bubbling up:
- Mongo::Error::OperationFailure: interrupted at shutdown (11600)
- Mongo::Error::OperationFailure: not master and slaveOk=false
- Mongo::Error::NoServerAvailable: No server is available matching preference
- Timeout::Error · Took more than 10 seconds to receive data.
    - Caused By: IO::EAGAINWaitReadable · Resource temporarily unavailable - errno backtraces disabled; run with -Xerrno.backtrace=true to enable

It is possible that some of the errors were because it exceeded its number of retries.

When running mongo queries and we get a timeout under that condition we would not want to keep retrying the query since it could be a bad query (missing index etc.). Maybe looking at the caused by exception may shed some light on the cause of the timeout before retrying.
The timeout error above occurred during what is normally a very quick find operation though.

**Comment by jarthod** [comment]
Good point about the Timeout, in my case it was also during very short operations and the timeout is set at 180s (just to avoid blocking forever basically), the `caused by` is `IO::EAGAINWaitReadable
Resource temporarily unavailable - read would block` in my case (probably same as yours), I'll have to check if it's different for an actually long query without network issue, if it is we may be able to retry only when needed.

**Comment by jarthod** [comment]
I had a look at the `OperationFailure` retries and noticed that actually the "interrupted at shutdown" and "not master and slaveOk=false" errors are supposed to be retry according the [retryable error code list](https://github.com/mongodb/mongo-ruby-driver/blob/b147f783459baa2ce8e397dad59a7ae67f32c194/lib/mongo/error/operation_failure.rb#L29) (Initially I only looked at the list of retryable writes by message)

I tried to verify if all the occurrences I had had been retried once but It was 1 month ago and I don't have the detailed logs any more. I'll probably have a another look on the next fail over. If you have any traces and can have a look if they were properly retried ("Retry due to ...") that would be good too.

**Pull request merged**
